[build]
  functions = "functions"
  
[[redirects]]
  from = "/tapeDown"
  to = "/.netlify/functions/tapeDown"
  status = 200

  [[redirects]]
  from = "/tapeMove"
  to = "/.netlify/functions/tapeMove"
  status = 200

  [[redirects]]
  from = "/tapeUp"
  to = "/.netlify/functions/tapeUp"
  status = 200